### PR TITLE
Feature/checkpoint : add the possibility to do live backups

### PR DESCRIPTION
**Pull request by benoitc**
See http://rocksdb.org/blog/2609/use-checkpoints-for-efficient-snapshots/  for more infos

### CODE REVIEW

**Comment by benoitc** [comment]
this change extract the checkpoint patch from #11

**Comment by mocchira** [comment]
@benoitc Thanks as always.

I'd like you to
1. Remove the commit `bump rocksdb...`
2. Add a test case
   to confirm whether iterator operations also works properly on a db created by Checkpoint 
3. `delete checkpoint`
   instead of `checkpoint = NULL;`

**Comment by benoitc** [comment]
@mocchira done
- added iterator test
- fixed C code to use `delete`
- rebased.

**Comment by mocchira** [comment]
LGTM.
Thank you for your contribution.

**Pull request merged**
