### PR TITLE
add full snapshot support to erocksdb

### PR DESCRIPTION
**Pull request by benoitc**
Snapshots are documented here:
https://github.com/facebook/rocksdb/wiki/Basic-Operations#snapshots

This change add `erocksdb:snapshot/1` and `erocksdb:release_snapshot/1` function.
Once created a Snapshot handle can be used in place of the Db handle in the the functions `erocksdb:iterator/2`' and  `erocksdb:get/3` functions.

See the snapshot_test module as an example

### CODE REVIEW

**Comment by mocchira** [comment]
@benoitc Thanks.
Please check out the below review result.
1. Divide the Checkpoint feature into an another PR
   To keep this PR a little bit simple.
2. Make the I/F consistent with the RocksDB
   Since Snapshot is specified via read_option in RocksDB, erocksdb also should do.
3. Add test cases
   - Check to work properly in case of more than 3 snapshot instances exist.
   - Check to `erocksdb:close` properly without closing snapshot instances.
4. Get rid of `-g -DDEBUG` compile params
5. where to place `*`pointer arithmetic
   - `Type* a` <- We will make the whole code consistent with this style. so please comply with that.
   - `Type *a`
   - `Type * a`

**Comment by benoitc** [comment]
Thanks for the review I will make the changes.

Though I disagree about `erocksdb:close` change. If the database close it is expected that the snapshot don't survive to it and is correctly freed. It should then be closed like iterators when the database is closed. This what does the code right now. Thoughts?

**Comment by mocchira** [comment]
@benoitc 

> Though I disagree about erocksdb:close change. If the database close it is expected that the 
> snapshot don't survive to it and is correctly freed. It should then be closed like iterators when the
> database is closed. This what does the code right now.

Yes I also expect what does the code rigtht now.

What I mean the below sentence is 

> Check to erocksdb:close properly without closing snapshot instances.

Since there is no test code to check that   `If the database close it is expected that the snapshot don't survive to it and is correctly freed`,
I'd ask you to add a test to confirm whether the above behavior is properly done.
(Any unreleased snapshots should be freed when  `erocksdb:close` is called.

**Comment by benoitc** [comment]
@mocchira OK I did the changes. While I was there I rebased the diff to make the commit atomic.

So this PR add the following:
- `erocksdb:snapshot/1` and èrocksdb:release_snapshot/1`  functions. They return a new Snapshot handle
- The snapshot handle can be passed in read_options for the functions `erocksdb:get/{3,4}` and  `erocksdb:iterator/{2,3}`.
- snapshot is freed when the db is closed
- when the snapshot is released it can't be used anymore as well.
- C style have been fixed

Tests have been added in `test/snapsho.erl` . Hopefully I didn't miss anything. Let me know.

**Comment by mocchira** [comment]
@benoitc Almost perfect.
There are still some pointer arithmetic inconsistencies but those coding rule will be fixed later by our code formatter.

Thank you for your contribution.

**Comment by benoitc** [comment]
thanks! out of curiosity what. do you use as code formatter?

**Comment by mocchira** [comment]
@benoitc http://astyle.sourceforge.net/
Since we(leo-project members) are discussing about the coding rule for C++ ( because recently we(currently only me) start to  write lots of code written in C++11 ),
we'll share the specific rule in future.

**Pull request merged**
